### ISSUE TITLE
How can I enable decorators?

### ISSUE THREAD

**Issue by p-adams** [infernojs/inferno-boilerplate#1]
I am trying to use inferno-mobx binding with inferno-boilerplate but I cannot enable decorators. I tried adding plugin `transform-decorators-legacy` to `.babelrc` but it did not work.

**Comment by nightwolfz** [comment]
@p-adams I will check now

**Comment by trueadm** [comment]
@p-adams what version of `inferno-mobx` have you installed locally, the `1.0.0-beta5` version?

**Comment by nightwolfz** [comment]
@p-adams Change your `.babelrc` to

```
{
    "env": {
        "development": {
          "presets": [
              "es2015",
              "stage-0"
          ],
          "plugins": [
            "transform-decorators-legacy",
            "babel-plugin-syntax-jsx",
            "babel-plugin-inferno"
          ]
        }
    },
    "plugins": [
      "transform-decorators-legacy",
      "babel-plugin-syntax-jsx",
      "babel-plugin-inferno"
    ]
}
```

**Comment by p-adams** [comment]
@trueadm `inferno-mobx@1.0.0-beta6`

**Comment by p-adams** [comment]
@nightwolfz That fixed it. Thanks!
