### ISSUE TITLE
webpack-cli should be a devDep

### ISSUE THREAD

**Issue by einar-hjortdal** [infernojs/inferno-boilerplate#11]
webpack-cli shouldn't be bundled, I think it should be a devDependency instead.

**Comment by Havunen** [comment]
webpack-cli is used to initialize production build script, https://github.com/infernojs/inferno-boilerplate/blob/master/package.json#L8  I think the logic in this boilerplate is that dependencies are the packages which are needed to create the production bundle and devDependencies are the ones that are needed for development work

**Comment by einar-hjortdal** [comment]
The general assumption is that packages that are not required for the production build to run are meant to be devDependencies. 

Though I understand your point of view and  ultimately it doesn't really matter to webpack, but the convention I've been conditioned to see is not respected here and making this boilerplate an outlier may be confusing other people needlessly

**Comment by Havunen** [comment]
yeah in this boilerplate only public folder should be shipped to production, nothing else
