### ISSUE TITLE
Boilerplate does not build correctly

### ISSUE THREAD

**Issue by florianeckerstorfer** [infernojs/inferno-boilerplate#3]
I tried to get the boilerplate running but it seems that it does not build correctly. I get a blank white page and the following error in the browser.

`Uncaught ReferenceError: Inferno is not defined`

**Steps**

1. `git clone git@github.com:infernojs/inferno-boilerplate.git
2. `cd inferno-boilerplate`
3. `npm install`
4. `npm start`

**Comment by florianeckerstorfer** [comment]
This has been fixed by 18841893318dabf05471b813eb559ed3851a1f1c. Thanks.

**Comment by Havunen** [comment]
No problem :)
