### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by szkrd** [infernojs/inferno-boilerplate#4]
Hi! The project has eslint, but no eslintrc (webstorm complained a bit about it) - probably semistandard would be fine, but not really sure if it's intentional. Thanks!

**Comment by Havunen** [comment]
Good point. We could use this one https://www.npmjs.com/package/eslint-config-inferno-app

**Comment by szkrd** [comment]
Oh, didn't know about it, mostly used standard/semistandard, thanks!

**Comment by Havunen** [comment]
Added eslint also there

**Comment by szkrd** [comment]
npm run lint works, thanks!
