### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by einar-hjortdal** [infernojs/inferno-boilerplate#9]
This is outdated, even more than create-inferno-app.
Please maintain one minimal boilerplate up to date to facilitate adoption.

**Comment by Havunen** [comment]
Hmm, yeah I could update this example. If you are interested using typescript, this is a good one: https://github.com/infernojs/inferno-typescript-example

**Comment by einar-hjortdal** [comment]
> Hmm, yeah I could update this example. If you are interested using typescript, this is a good one: https://github.com/infernojs/inferno-typescript-example

I see that one is up to date but I use Flow and Less over TS and Sass

I think a very basic boilerplate would be best to start with

**Comment by Havunen** [comment]
All dependencies are now updated to latest versions
